cc_library(
    name = "pico-ads1115",
    srcs = ["ads1115.cpp"],
    hdrs = glob(["include/*.h"]),
    deps = [
        "@pico-sdk//src/rp2_common/hardware_i2c:hardware_i2c",
        "@pico-sdk//src/rp2_common/pico_stdlib:pico_stdlib",
    ],
)
